server:
  port: 8081


spring:
  application:
    name: order-service-api

  datasource:
    url: jdbc:mysql://localhost:3306/eadp_order_api_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka